### PR TITLE
Feature/update box wrapper and ocr

### PR DESCRIPTION
**Pull request by Daos21912**
## Co-Authors:
Amadou N'Gom
Hunter Jordan
Jackson Reber
Peter Rockwood
Yousef Al-Yakoob

## Description

Changed Box wrapper class to export data as python native objects, and changed document processor class to simply return text

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

Loom: https://www.loom.com/share/b87d0d73029b4d20a106fe6f7fa8107a

### CODE REVIEW

**Review by theawesomejaik — APPROVED** [review]
Great simplification here. Love to see it.

**Review by engegreg — APPROVED** [review]
Fantastic implementation, this opens a lot of functionality for the application. Definitely should be approved.

**Review by m-rath — APPROVED** [review]
Great changes!  I encourage everyone to watch the Loom recording from Dan.  Several significant, thoughtful improvements.  Good work, Peter, sorting out the DPI parameter there, too.

**Review by yalyakoob — APPROVED** [review]
Awesome improvements. Good work in only having to instantiate the box wrapper class once.

**Review by HunterJordan — APPROVED** [review]
Awesome walk through and implementation Dan!

**Review by benclowe29 — APPROVED** [review]

**Review by prockwood — APPROVED** [review]
Looks great! Nice explanation. I think the more modular approach is a good way to go. I'd love to hear about static methods from you some time. Dan gets shit done!

**Review by Amadou23 — APPROVED** [review]

**Review by lucchesia7 — APPROVED** [review]

**Review by dagtag — APPROVED** [review]
Wonderful improvements, and a very clear and thorough loom video to explain changes.  Definitely ready for merging!

**Review by madina-iz — APPROVED** [review]

**Comment by dagtag** [comment]
[Link box API wrapper to Tesseract](https://trello.com/c/zmw1fUDt/60-link-box-api-wrapper-to-tesseract)

**Pull request merged**
