### PR TITLE
Feature/backup

### PR DESCRIPTION
**Pull request by jinjahninjah**
## Description

We also added a new method to handle the backup feature. 

## Participants

- Xiao Song
- Luke Sislowski
- Robert Sharp

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by BrokenShell — APPROVED** [review]
Excellent work! This is exactly what we worked on together in the DS Workshop. Great Job!!!

**Review by xsong0306 — APPROVED** [review]
Thank you, Robert, Royce, and Luke!!

**Comment by LSislowski** [comment]
Good work on creating an endpoint together! Thanks to Robert for the help as well.

**Review by LSislowski — APPROVED** [review]
Good work on creating an endpoint together! Thanks to Robert for the help as well.

**Pull request merged**
