### PR TITLE
added me, myself, and I 

### PR DESCRIPTION
**Pull request by theawesomejaik**
## Description

I'm here. Notice me senpai!

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by JacksonReber — APPROVED** [review]
Love this Jake! Thanks for keeping the ReadMe's up to date

**Review by Daos21912 — APPROVED** [review]
Shouldn't we all do something similar?

**Review by HunterJordan — APPROVED** [review]
Nice Jake! We need more DS to claim their contribution!

**Review by dagtag — APPROVED** [review]
You're missing a PR video, but your name looks great!  No spelling errors.

**Review by yalyakoob — APPROVED** [review]
Great addition. Looks good!

**Review by paulstgermain — APPROVED** [review]
As this was an early PR for @theawesomejaik, and the description made me laugh, I'm going to approve of this one. 

That said, in the future be sure NOT to submit PRs of only 1 line in length wherever possible, especially if those are cosmetic changes to documentation - and let's not forget our Loom recordings!

**Pull request merged**
