### PR TITLE
import statement fix, static method change to function, rename functi…

### PR DESCRIPTION
**Pull request by yalyakoob**
Please give additional pull request credit to the following co-contributors:
-Alyssa Murray 
-Alex Lucchesi
-Dan Ferber 
-Ben Clowe 
-Hunter Jordan 
-Jackson Reber
-Jake Harris
-Jeremy Hebert
-Mark Porath 
-Peter Rockwood

## Description

-Changed the get_text  from a static method in a class to a function
-Renamed 'get_text' function to 'ocr' for better readability
-Fixed the import statement bug from .box_wrapper to app.box_wrapper
** No video is necessary as these changes were discussed in DS office hours with the DS team. 
Fixes # (issue)
3

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by Daos21912 — APPROVED** [review]

**Review by dagtag — APPROVED** [review]
Great implementation from office hours Youssef!

**Comment by dagtag** [comment]
[As a user I want to clean up OCR file to reflect 1 function instead of 1 class](https://trello.com/c/ye8pLwr4/91-as-a-user-i-want-to-clean-up-ocr-file-to-reflect-1-function-instead-of-1-class)

**Comment by engegreg** [comment]
clean implementation. I'm a fan of changing over from a static method in this case.

**Review by HunterJordan — APPROVED** [review]

**Review by rishimaru23 — APPROVED** [review]

**Review by lucchesia7 — APPROVED** [review]

**Review by prockwood — APPROVED** [review]
Well done sir!

**Review by JacksonReber — APPROVED** [review]
Great job using the static method here, I love it!

**Review by BrokenShell — APPROVED** [review]
Very good. Just as we did together in office hours.

**Review by m-rath — APPROVED** [review]
good pointers, Robert. Thank you.

**Review by jhebert1994 — APPROVED** [review]
Reviewed this change as a group so we know the code still works and should help save resources.

**Pull request merged**
