### PR TITLE
added diagram to assets folder and to README.md

### PR DESCRIPTION
**Pull request by m-rath**
## Description

Mark Porath, Alex Lucchesi, Alyssa Murray, Ben Clowe

Where do the DS components reside? How do they connect?

A new structural diagram in the assets folder and README.md illustrates the DS architecture, with placeholders for the front end and back end. Discussion and planning are easier with a shared visual.

This diagram is a draft. It is consistent with our plan, but will no doubt need revision when more details and goals become clear.

https://user-images.githubusercontent.com/69127760/140232959-f87d67af-c5ae-4d6b-b8dd-a5948a84b25c.mp4

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yalyakoob — APPROVED** [review]
Looks good, Mark!

**Review by Daos21912 — COMMENTED** [review]
Just a thought, but shouldn't our API be connected to back end, rather than front end? Otherwise, I think this is a great idea to have in our repo, and if I'm wrong I'll happily approve.

**Review by madina-iz — APPROVED** [review]
Great diagram and a nice walk though in the video. Quick question just out of curiosity.. So, we decided to utilize the links to box files after all, so users can click on them to see the original docs?

**Comment by dagtag** [comment]
[Drawing up architecture diagram](https://trello.com/c/oimNWzFU/55-drawing-up-architecture-diagram)

**Review by theawesomejaik — COMMENTED** [review]
I agree with Dan that I'm confused on why the diagram points DS to FE rather than BE. Please clarify if this is the correct diagram.

**Comment by dagtag** [comment]
@theawesomejaik @Daos21912 this might be a good question for @tdubs42 ?  In the video (minute 2:30) he says she reported they wanted the DS API to hand off directly to front end. We definitely need some clarification on that!

**Pull request merged**
