### PR TITLE
Update ReadMe/Add Research.md

### PR DESCRIPTION
**Pull request by lucchesia7**
# Paul: Pair Programming completed with:
Alyssa Murray
Mark Porath
Peter Rockwood

Updated ReadMe.md to reflect all active members of LABS 40 DS. Removed two sections of research and consolidated into single file and added research completed by team. Linked file to ReadMe.md Updated Python Badge to work properly and display v 3.7, 3.8, and 3.9

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://user-images.githubusercontent.com/84862301/140551417-3a0e13a8-1a86-485f-a611-26c1e4e9da75.mp4

### CODE REVIEW

**Review by Daos21912 — APPROVED** [review]
This is a good documentation update. Thanks for your hard work!

**Review by benclowe29 — APPROVED** [review]

**Review by yalyakoob — APPROVED** [review]

**Review by HunterJordan — APPROVED** [review]

**Review by prockwood — APPROVED** [review]
Very nice improvement. The link to our mondoDB research is in a branch right now. We were gonna meet again this afternoon and make a pull request. So you may need to change that link when it gets merged to main.

**Review by dagtag — APPROVED** [review]
We just need to take out Mayra's name as a contributor in the next PR!

**Comment by tdubs42** [comment]
[Update DS ReadMe and create new research.md file to store all DS Research](https://trello.com/c/alGY4ZIz/61-update-ds-readme-research-from-team-c-on-flow-from-box-tesseract)

**Comment by dagtag** [comment]
[Explore MongoDB Capabilities](https://trello.com/c/R8YuL9cE/66-explore-mongodb-capabilities)

**Pull request merged**
