### PR TITLE
changed uvicorn dependencies

### PR DESCRIPTION
**Pull request by engegreg**
## Description
Co-Contributors: Robert Sharp, Dan Ferber, Mark Porath

In the requirements.txt folder, there were a series of uvicorn imports that Robert found which were causing issues with deployment. Once the solution was found we made a basic adjustment to the requirements.txt folder.  

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said change

https://user-images.githubusercontent.com/44015442/140245727-7414952f-1123-4324-9aac-8656d81c558e.mp4

### CODE REVIEW

**Review by Daos21912 — APPROVED** [review]
This is exactly what we talked about. Thanks for making this change!

**Review by m-rath — APPROVED** [review]
Looks good, Greg. Thanks for not only fixing this for us, but also explaining the details in the video. As Robert pointed out, this kind of issue with Docker is not an easy bug to identify. Good to have the issue on record -- both the problem and the fix. Good PR.

**Review by dagtag — APPROVED** [review]
Solid update.  All looks good!

**Review by BrokenShell — APPROVED** [review]
perfect

**Review by prockwood — APPROVED** [review]
Good find, nice explanation, Greg.

**Comment by dagtag** [comment]
[DS API needs a deployment compatibility update](https://trello.com/c/I66BUiPn/70-ds-api-needs-a-deployment-compatibility-update)

**Review by lucchesia7 — APPROVED** [review]

**Review by madina-iz — APPROVED** [review]
Great fix!

**Pull request merged**
