### PR TITLE
Update nlp.py

### PR DESCRIPTION
**Pull request by lucchesia7**
**Paul: Please give credit to the following people for this PR**
* Alyssa Murray
* Dan Ferber
* Peter Rockwood
* Jackson Reber
* Jake Harris
* Hunter Jackson
* Ben Clowe
* Youssef Al-Yakoob
* Jeremy Hebert
* Mark Porath

https://user-images.githubusercontent.com/84862301/140981762-2fa3484f-24e0-43df-b8ac-8c1e1942c06f.mp4

## Description

During our DS OH today, we reviewed the NLP.py file. We learned of the issues that may arise from removing all punctuation before NLP and how to handle whitespaces. The changes in this code reflect the learnings from today.

* Removed punctuation regex completely.
* Edited whitespace regex to be all-inclusive of any form of whitespace.
* Changed return statement to use less computational power, yet achieve same result.

Fixes # (issue)
3

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yalyakoob — APPROVED** [review]

**Review by galtman5 — APPROVED** [review]

**Review by Daos21912 — APPROVED** [review]

**Review by engegreg — APPROVED** [review]
Considerable improvement, simplifying the regex will have a noticeable improvement on runtime and efficiency. Really good find.

**Review by dagtag — APPROVED** [review]
Great implementation from our DS Office Hours today!

**Comment by dagtag** [comment]
[As a user I want to Update Nlp.py file to run the entities function on raw text output from Dan's output](https://trello.com/c/PwIqa9d6/92-as-a-user-i-want-to-update-nlppy-file-to-run-the-entities-function-on-raw-text-output-from-dans-output)

**Review by benclowe29 — APPROVED** [review]

**Review by HunterJordan — APPROVED** [review]

**Review by rishimaru23 — APPROVED** [review]

**Review by theawesomejaik — APPROVED** [review]
Amazing work as always Alex. Thanks for pushing out one of our office hours tickets

**Review by prockwood — APPROVED** [review]
Good changes, very explanation/

**Review by JacksonReber — APPROVED** [review]
Thanks for submitting this Alex, we all worked on this together and your Loom video does a great job of explaining the changes.

**Review by Amadou23 — APPROVED** [review]

**Review by BrokenShell — APPROVED** [review]
Very good. Just as we worked on together in office hours. We may want to keep working on this to reduce the number of tags and increase their relevance.

**Review by m-rath — APPROVED** [review]
Sure, punctuation could help at this step. Thanks

**Review by jhebert1994 — APPROVED** [review]
Good catch, if we stripped all punctuation it definitely would of had a negative effect on the text

**Pull request merged**
