### PR TITLE
Feature/dpi analysis

### PR DESCRIPTION
**Pull request by prockwood**
## Description

Including the results of an analysis to determine a good dpi setting for pdf_conversion.

Contributors: Peter Rockwood, Guy Altman

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

[loom video](https://www.loom.com/share/cdd621a064e64880a591e62917e7be9c) oops! shared the wrong screen, second try.
[trello card](https://trello.com/c/a4VSqoqI/99-as-a-user-i-want-to-find-a-good-dpi-setting-for-tesseract)

### CODE REVIEW

**Review by Daos21912 — APPROVED** [review]
Thanks for this great research!

**Comment by lucchesia7** [comment]
[As a user I want to find a good dpi setting for tesseract](https://trello.com/c/a4VSqoqI/99-as-a-user-i-want-to-find-a-good-dpi-setting-for-tesseract)

**Review by lucchesia7 — APPROVED** [review]
This is great. You did a wonderful job in documenting your research here. Anyone stepping into this project, even with limited knowledge of tesseract and ocr, can understand your dpi analysis and implement your findings. You went above and beyond in your analysis and research findings. Thank you for this!

**Review by dagtag — APPROVED** [review]
Way to blow it out of the water with this research!  You guys always go above and beyond.  It will be a great resource for the next team stepping in.

**Review by m-rath — APPROVED** [review]
great video. I appreciate the graphs, too. well done. let the ocr begin!

**Review by JacksonReber — APPROVED** [review]
This is great research! I think this is important information for our next steps.

**Review by jhebert1994 — APPROVED** [review]
Great research, always nice to see a why behind such an important setting such as dpi. This will definitely give clarity to anyone in the future working on this section of the project.

**Review by engegreg — APPROVED** [review]
quality research, great job.

**Pull request merged**
