### PR TITLE
Feature/docview endpoint

### PR DESCRIPTION
**Pull request by engegreg**
## Description

We created a new endpoint for querying files based on their file id. The endpoint (titled Docview) will pull files based on their associated id, and can pull multiple files in one search. 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said change

https://user-images.githubusercontent.com/44015442/141522115-bec836bb-8e2e-4a02-a65b-4ac0e9b028cf.mp4

### CODE REVIEW

**Review by lucchesia7 — APPROVED** [review]

**Review by dagtag — APPROVED** [review]
Looks good you guys!  I'm confused why the PR says it's adding insert_data.py though, that was already merged, right?  My understanding of Github isn't wonderful yet though, so I'm sure it's just be being dumb!

**Comment by engegreg** [comment]
> Looks good you guys! I'm confused why the PR says it's adding insert_data.py though, that was already merged, right? My understanding of Github isn't wonderful yet though, so I'm sure it's just me being dumb!

It's because the branch we were working in did not have insert_data.py, since it was behind a bit.

**Review by prockwood — APPROVED** [review]
Lots of features added here! Nice work! Seems to address front-end's request for doc by ID getter. Maybe just make sure we aren't changing insert_data.py with this merge.

**Comment by dagtag** [comment]
[Add endpoint for document view, and update search endpoint](https://trello.com/c/O3oP2xJZ/102-add-endpoint-for-document-view-and-update-search-endpoint)

**Pull request merged**
