### PR TITLE
Feature/mongo insert script

### PR DESCRIPTION
**Pull request by lucchesia7**
**Paul: The following people were contributors to this PR:**
* Dan Ferber
* Peter Rockwood
* Hunter Jordan
* Jackson Reber
* Jake Harris
* Ben Clowe
* Greg Englemann
* Guy Altman

https://user-images.githubusercontent.com/84862301/141346109-4550172e-ffd2-44cb-a2fc-f0153fed2cfe.mp4

## Description

We have created a script which ties together all the DS components thus far. We are now able to move our .pdf's from Box API into Tesseract for OCR, through SpaCy for NER tagging and then into a MongoDB instance.

Fixes # (issue)
1

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yalyakoob — APPROVED** [review]
Very well structured and readable code. Well done!

**Comment by lucchesia7** [comment]
[As a user I want to write a script that gets a list of files inside a list of folders for insertion into Mongo](https://trello.com/c/ehtXDOV1/90-as-a-user-i-want-to-write-a-script-that-gets-a-list-of-files-inside-a-list-of-folders-for-insertion-into-mongo)

**Comment by lucchesia7** [comment]
[MongoDB Structuring](https://trello.com/c/ID9Qz7n0/47-mongodb-structuring)

**Review by engegreg — APPROVED** [review]
probably the most streamlined way we can interact with mongo. Great implementation.

**Review by dagtag — APPROVED** [review]
Elegantly written code, very readable.  Love the implementation of the closed folder, completed folder, closed file progress report that will be displayed while it's running.  Amazing work you guys!

**Review by JacksonReber — APPROVED** [review]
Excellent description Alex. This will be extremely valuable when we populate the Mongo database

**Review by jhebert1994 — APPROVED** [review]
Very readable and efficient code, looking forward to seeing what we can do once these docs are in our db.

**Pull request merged**
