### PR TITLE
add date extraction to nlp

### PR DESCRIPTION
**Pull request by madina-iz**
## Description

Co-authors: Youssef Al-Yakoob and Guy Altman.

Added code to extract years from text data using SpaCy NER. The code by design only extracts 4-digit years in order to limit the type of output and exclude such date types as days of a week and stand alone months, etc.

For the purposes of processing efficiency the years extraction code was incorporated into the existing function that extracts named entities, so RegEx and SpaCy object instantiation is performed just once for each text.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://user-images.githubusercontent.com/84870668/141182508-6db6cced-821b-43c9-8093-ddf7a51e7fc3.mp4

### CODE REVIEW

**Comment by madina-iz** [comment]
[Stretch: As a user I want to use Spacy to identify dates in documents](https://trello.com/c/8wvI68fg/93-stretch-as-a-user-i-want-to-use-spacy-to-identify-dates-in-documents)

**Review by collerhatguy — APPROVED** [review]
comments are important. often people write comments for code and then forget to update the comment when its refactored later. Good job remembering to do that.

**Review by yalyakoob — APPROVED** [review]
Great Work!

**Review by prockwood — APPROVED** [review]
Good addition, I think years might be pretty important to the researchers. One thing: Robert had us remove 'text = re.sub('[^ A-Za-z0-9]', ' ', text)'  and he changed 'text = re.sub('  +', ' ', text)' to 'text = re.sub(r'\s+', ' ', text)' yesterday during DS workshop. I think those changes are merged in the main branch.

**Pull request merged**
