### PR TITLE
added PEGASUS info to README.md

### PR DESCRIPTION
**Pull request by m-rath**
## Description

Added a section called "Research" to README.md, just above the "Contributors" section.

Under that Research heading, added two bullets and several links about automated document summarization, an NLP technique that would serve the stakeholder's needs.  Specifically, if the researchers using this app want to see brief summaries of documents before linking to the full text, PEGASUS offers one way to provide those summaries.

PEGASUS provides one type of abstractive summary.  Note that abstractive summaries are not the same as query-specific summaries, which would no doubt prove useful to the researchers, as well.

https://user-images.githubusercontent.com/69127760/139707488-03c58083-d176-4f08-82b6-5e87b49c69ae.mp4

## Type of change

- [x] Research with link to technical tool

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

### CODE REVIEW

**Review by yalyakoob — APPROVED** [review]
Looks good to me!

**Review by benclowe29 — APPROVED** [review]
Thanks for digging into this.  Looks good!

**Review by galtman5 — APPROVED** [review]
Nice find!

**Comment by benclowe29** [comment]
[Research Document Summarization](https://trello.com/c/tQzqbs79/54-research-document-summarization)

**Review by prockwood — COMMENTED** [review]
Super interesting! I might hold off on approving until Greg's fixes get merged. Also I'm feeling like this advanced NLP stuff would be really cool to implement, but maybe we should focus on getting a simple use-case working (namely full-text search) before we jump into state-of-the-art methods. That's just my conservative disposition talking, I could be wrong, it's worth a discussion I reckon.

**Review by HunterJordan — APPROVED** [review]
Looks good, great documentation to follow with it.

**Review by paulstgermain — APPROVED** [review]
## Video Walkthrough Review

This is a SOLID walkthrough for this PR! You made a small, but important, change to the repo's `README`, and thoroughly explained its significance by walking us quickly through the research you've done and links you've sourced and added. Great work!

## Code Review

Small change to the `README`, but a huge value-add for our team and the researchers who may use this moving forward - nice work!

**Pull request merged**
