### PR TITLE
fixed broken python badge on readme file

### PR DESCRIPTION
**Pull request by yalyakoob**
coauthored with: Mark Porath and Guy Altman

## Description
The Python badge on readme was broken. We added a working badge. Added DS team contributors to readme file.

Fixes # (issue)
1

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said change

https://user-images.githubusercontent.com/61222734/139477976-589962cc-e7f5-4dcb-bb2f-2fbfd769cb24.mp4

### CODE REVIEW

**Review by dagtag — APPROVED** [review]
The 3 added names look perfect and the python badge looks appropriate.  Thanks for catching that Youssef, Mark and Guy!

**Review by theawesomejaik — APPROVED** [review]
good job guys.

**Review by HunterJordan — APPROVED** [review]
Looking good!

**Review by Daos21912 — APPROVED** [review]
Looks good to me

**Review by JacksonReber — APPROVED** [review]
Thanks for fixing the badge, makes it look more professional! Good job

**Review by bverfurth — APPROVED** [review]
This all looks great! Good job!

**Pull request merged**
